// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmYTiGuat9n2Ozdt20gF5GshJLHnobtOc',
    appId: '1:317782252495:web:78c867ecb339d940f910ba',
    messagingSenderId: '317782252495',
    projectId: 'mobileauthentication-5144f',
    authDomain: 'mobileauthentication-5144f.firebaseapp.com',
    storageBucket: 'mobileauthentication-5144f.firebasestorage.app',
    measurementId: 'G-JEKT7CT1H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB15djNTWdcCnoOKFjjMWx76c_kDl84BCI',
    appId: '1:317782252495:android:ff1a0954da925e30f910ba',
    messagingSenderId: '317782252495',
    projectId: 'mobileauthentication-5144f',
    storageBucket: 'mobileauthentication-5144f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSOOiczknwTycOEPav1wh0NmkRiKOrcUo',
    appId: '1:317782252495:ios:d41064463f81048cf910ba',
    messagingSenderId: '317782252495',
    projectId: 'mobileauthentication-5144f',
    storageBucket: 'mobileauthentication-5144f.firebasestorage.app',
    iosBundleId: 'com.example.mobileAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSOOiczknwTycOEPav1wh0NmkRiKOrcUo',
    appId: '1:317782252495:ios:d41064463f81048cf910ba',
    messagingSenderId: '317782252495',
    projectId: 'mobileauthentication-5144f',
    storageBucket: 'mobileauthentication-5144f.firebasestorage.app',
    iosBundleId: 'com.example.mobileAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmYTiGuat9n2Ozdt20gF5GshJLHnobtOc',
    appId: '1:317782252495:web:f9995f8d99799458f910ba',
    messagingSenderId: '317782252495',
    projectId: 'mobileauthentication-5144f',
    authDomain: 'mobileauthentication-5144f.firebaseapp.com',
    storageBucket: 'mobileauthentication-5144f.firebasestorage.app',
    measurementId: 'G-0CMDLK1RVF',
  );
}
